apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
  namespace: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      labels:
        app: inventory-api
    spec:
      containers:
        - name: inventory-api
          image: ghcr.io/ronaldt1/inventory-api-dvps:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-config
          env:
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: JWT_KEY
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: api-db-secret
                  key: ConnectionStrings__DefaultConnection
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
